### ISSUE TITLE
Rename might cause build issue

### ISSUE THREAD

**Issue by dastein1** [jonasbark/openapi_dart#2]
I tried this builder on an openapi yaml called `insights.openapi.yaml`.  
The builder generates an `insights.openapi.dart` file (as expected) and then after some delay renames that file to `insights.dart`.

In my case though the build_runner is then complaining `AssetNotFoundException: insights_app|lib/models/openapi/insights.openapi.dart`.  
That actually makes sense the last build step renamed that file but the builder is not aware of that.

I tried to get rid of that last rename step, however, freezed is then not picking it up and generating the part files.
The only solution that I've found is to copy that file and leave the originally generated file in place.
Do you have any idea how that could be solved more _nicely_?

**Comment by jonasbark** [comment]
Fixed with version 0.9.4 - thanks again
